### ISSUE TITLE
Allscripts profession EHR failing

### ISSUE THREAD

**Issue by dhf0820** [kdar/health#10]
I pulled a new CCD from Allscripts today and it fails on Vital Signs.  I removed all except the first one and it passes. I removed the first one and ran tests by having only one of the next three entries by them slves and they each failed.  The only way it works is with the first one.  Would you like a copy of the test CCD?

**Comment by kdar** [comment]
Sure, as long as there is no sensitive patient information.

**Comment by dhf0820** [comment]
This is the test data from AllScripts sand box.  It is not real data. PHI is there however it is fake.

It is odd that with just the first vita only l it works, replacing it with the second, third, and fourth it fails.  I did not go past that.

Thank you a great library. I am learning both GO and CDA.  I have been in healthcare IT since 1989.

Don French

**Comment by kdar** [comment]
I still don't see a link to the CCD. I don't believe email attachments make it to Github comments.

**Comment by dhf0820** [comment]
I can email direct it is 800k

**Comment by kdar** [comment]
Waiting on that email :).

**Comment by dhf0820** [comment]
I need a real email. You said it did not go through when I email it through github.

**Comment by kdar** [comment]
It's on my github profile page.

**Comment by dhf0820** [comment]
Thanks, it seems to work well. Still have more testing to do.

Did you know that on vital_signs the observation name is blank. I can find it in the code.displayname, however should it not be in the Observation.name also?

Don French

**Comment by kdar** [comment]
Actually VitalSignObservation.Name should not be there. VitalSignObservation.Code.DisplayName is what you want.
