### ISSUE TITLE
question about simple.hl7

### ISSUE THREAD

**Issue by pegli** [kdar/health#4]
I'm working on a PR that adds a HL7 encoder to the project and am reusing the existing test files to ensure that it works properly.  The encoder can re-create sample.hl7 exactly at the moment, but it fails when trying to create simple.hl7.  `The decoder_test.go` file defines the decoded structure of that test file to be:

    Segment{
      Field("MSH"),
      Field("|"),
      Field(`^~\&`),
      Field("field"),
      Field(`\|~^&HEY`),
      ...

In particular, the fifth field should have a value of `\|~^&HEY`.  The sample.hl7 file reads differently, however:

    MSH|^~\&|field|\E\\F\\R\\S\\T\\X484559\|component1^component2

How does `\E\\F\\R\\S\\T\\X484559\` get decoded into `\|~^&HEY`?  The decoder test is passing on my laptop, so I feel like I'm missing something important.  Thanks for your help!

My code is here, if you would like to take a look:  https://github.com/pegli/health/tree/feature/hl7_encoder/hl7

**Comment by kdar** [comment]
Those are escape sequences. Look here for reference: http://www.hl7standards.com/blog/2006/11/02/hl7-escape-sequences/

**Comment by pegli** [comment]
Perfect, that's exactly what I needed to know.  I'll add escaping to my encoder and send a PR.
